<a href="https://colab.research.google.com/github/prodramp/python-projects/blob/main/Walmart-SuperMarket/Purchase_with_Stores_Viz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
master_store = 'https://github.com/prodramp/python-projects/raw/main/Walmart-SuperMarket/master_store_data.csv'

In [3]:
ca_purchase_history = 'https://github.com/prodramp/python-projects/raw/main/Walmart-SuperMarket/purchase_history_ca.csv'

In [28]:
user_address = 'https://github.com/prodramp/python-projects/raw/main/Walmart-SuperMarket/user_address.csv'

In [41]:
stores_with_geo = 'https://github.com/prodramp/python-projects/raw/main/Walmart-SuperMarket/stores_with_state_geo.csv'

In [10]:
purchase_ca = pd.read_csv(ca_purchase_history)

In [11]:
purchase_ca

,Unnamed: 0,order_number,purchase_date,family_id,order_total,qty,super_market_uuid,product_id,product_name,price
0,0,LXH-519933,2021-01-25 10:26:02,PffcRNJxYK,1,1,a197dfa1-3aa4-4d83-b1bf-8a6dac7530b3,11786,Free & Clear All-Purpose Natural Cleaner,12.76
1,1,axl-469572,2021-01-02 03:59:25,LnsjykTPKN,7,3,59046f82-3945-42a9-9403-c78a7fc340fd,30446,All Natural Chicken Livers,86.19
2,2,axl-469572,2021-01-02 03:59:25,LnsjykTPKN,7,2,59046f82-3945-42a9-9403-c78a7fc340fd,47952,"Soap, Buttermilk",52.90
3,3,axl-469572,2021-01-02 03:59:25,LnsjykTPKN,7,1,59046f82-3945-42a9-9403-c78a7fc340fd,20218,"Pancake & Waffle Mix, Six Grain Cinnamon",9.11
4,4,axl-469572,2021-01-02 03:59:25,LnsjykTPKN,7,2,59046f82-3945-42a9-9403-c78a7fc340fd,4697,"Eggs, Cheese & Turkey Sausage Breakfast Burrito",7.93
...,...,...,...,...,...,...,...,...,...,...
15647,15647,Ofv-743886,2020-12-25 11:12:21,YiyvpQxhVk,9,1,c757105f-0dae-4bdf-9a2b-9f1f68d085b0,13186,No Sugar No Salt No Stir Creamy Almond Butter,40.69
15648,15648,CwT-406296,2020-12-28 00:16:56,YiyvpQxhVk,1,4,c757105f-0dae-4bdf-9a2b-9f1f68d085b0,45365,Organic Peppermint,41.42
15649,15649,IHO-799497,2020-12-25 11:55:00,YiyvpQxhVk,3,3,c757105f-0dae-4bdf-9a2b-9f1f68d085b0,3812,Chocolate Fudge Topping,68.73
15650,15650,IHO-799497,2020-12-25 11:55:00,YiyvpQxhVk,3,1,c757105f-0dae-4bdf-9a2b-9f1f68d085b0,33494,Original Nasal Spray,20.79
15651,15651,IHO-799497,2020-12-25 11:55:00,YiyvpQxhVk,3,4,c757105f-0dae-4bdf-9a2b-9f1f68d085b0,18155,Healthy Mouth Tea Tree Oil & Cinnamon Toothpaste,28.26

In [6]:
all_stores = pd.read_csv(master_store)

In [7]:
all_stores

,Unnamed: 0,name,latitude,longitude,store_id
0,0,Conway Supercenter,35.108660,-92.436905,5eb5e7fc-88b6-4326-9f6f-c2bfee082258
1,1,Sikeston Supercenter,36.857394,-89.586051,03419f7a-e60f-4b7b-9bea-edff19c1a24a
2,2,Tahlequah Supercenter,35.888765,-94.979859,a7b1bc6a-17b6-4de1-ae2e-eecd653bf891
3,3,Mountain Home Supercenter,36.354957,-92.341026,bf317faf-d154-4980-a8d1-83161bfbbacf
4,4,Claremore Supercenter,36.293955,-95.627125,04508372-c00b-4e4c-a486-524e9730040f
...,...,...,...,...,...
4649,4649,Pearland Neighborhood Market,29.556350,-95.415783,8c4f0c6f-4cfb-40d9-8034-07d92f28ad03
4650,4650,Bentonville Gas Station,36.357486,-94.214669,c59fa17d-5db0-4fc9-87d7-d84a1944293d
4651,4651,Millcreek Pickup only,40.691031,-111.846529,c070b01a-bb77-4587-ab85-d7e29819f9c5
4652,4652,Dallas Supercenter,32.963412,-96.770294,25ffd0bb-0501-4418-801e-2f55f833f8f6
4653,4653,Murray Pickup only,40.649827,-111.849349,974573f3-e900-4b4c-bd49-5001805386a9

In [13]:
purchase_ca = purchase_ca[['family_id', 'super_market_uuid']]

In [14]:
purchase_ca

        family_id                     super_market_uuid
0      PffcRNJxYK  a197dfa1-3aa4-4d83-b1bf-8a6dac7530b3
1      LnsjykTPKN  59046f82-3945-42a9-9403-c78a7fc340fd
2      LnsjykTPKN  59046f82-3945-42a9-9403-c78a7fc340fd
3      LnsjykTPKN  59046f82-3945-42a9-9403-c78a7fc340fd
4      LnsjykTPKN  59046f82-3945-42a9-9403-c78a7fc340fd
...           ...                                   ...
15647  YiyvpQxhVk  c757105f-0dae-4bdf-9a2b-9f1f68d085b0
15648  YiyvpQxhVk  c757105f-0dae-4bdf-9a2b-9f1f68d085b0
15649  YiyvpQxhVk  c757105f-0dae-4bdf-9a2b-9f1f68d085b0
15650  YiyvpQxhVk  c757105f-0dae-4bdf-9a2b-9f1f68d085b0
15651  YiyvpQxhVk  c757105f-0dae-4bdf-9a2b-9f1f68d085b0

[15652 rows x 2 columns]

In [19]:
final_purchase_df = purchase_ca.groupby(['family_id', 'super_market_uuid']).size().to_frame(name='total').reset_index()

In [20]:
final_purchase_df

     family_id                     super_market_uuid  total
0   AmBEinMYuA  411056cb-ac50-4fff-b2dd-cb8cd8abeb2c    328
1   BrHcJPwbEN  411056cb-ac50-4fff-b2dd-cb8cd8abeb2c    323
2   CrrIMbxCqq  ad3f9a5b-bd16-4fa7-955f-a64efcbe0b73    256
3   DTkbsfedVz  ea4d744e-81be-4c5b-a9fe-6635bdc73898    319
4   EiYBogVros  c2ce04c8-903e-4cf8-a0c9-2e486c6505f8    301
..         ...                                   ...    ...
80  vKDywjAzZd  a08f28d3-8199-4ec8-9246-b2d753201981    335
81  vwBwugVAWN  419fbe0b-fe20-4402-85ab-3a02188518d1    221
82  yGPwyiMcbi  2b72db98-be02-4834-900f-70129f665910    146
83  yGPwyiMcbi  c7215c9d-c948-40c9-9436-87359f76087d    169
84  zbozWvFTfr  dc50cc89-f7ed-4469-a19e-b0f675ec0110    352

[85 rows x 3 columns]

In [29]:
df_address = pd.read_csv(user_address)

In [30]:
df_address

,Unnamed: 0,street_address,city,state,zip_code,longitude,latitude,family_id
0,0,3842 Foster Extension Suite 802,Kodiak,AK,99615,-152.435656,57.855664,zgwwktzKhQ
1,1,44321 Walker Keys Apt. 864,Anchorage,AK,99515,-149.922917,61.137293,pLWALrqnyh
2,2,2986 Bennett Islands,Fairbanks,AK,99701,-147.729893,64.964319,FOftMIWqih
3,3,87184 Heather Route,Anchorage,AK,99504,-149.787056,61.214061,HqRjqVkkKM
4,4,106 Garcia Landing Apt. 252,Fairbanks,AK,99701,-147.773499,64.971583,VhqYNluvOP
...,...,...,...,...,...,...,...,...
5195,5195,93514 Tony Heights Apt. 428,Laramie,WY,82070,-105.546594,41.370194,BmmGXjZtRO
5196,5196,75260 Sierra Locks,Rawlins,WY,82301,-107.239326,41.876562,ZLsJOksHPf
5197,5197,965 Jeff Tunnel,Riverton,WY,82501,-108.412675,43.018480,jJzbAKZtct
5198,5198,45003 Bianca Estate Apt. 574,Evanston,WY,82930,-111.014650,41.381744,vazbyRZeil
5199,5199,8412 Huynh Falls,Gillette,WY,82718,-105.526284,44.346204,ZWbzUlseJz

In [33]:
add_temp_df = pd.merge(final_purchase_df, df_address, how='left', on='family_id')
add_temp_df

,family_id,super_market_uuid,total,Unnamed: 0,street_address,city,state,zip_code,longitude,latitude
0,AmBEinMYuA,411056cb-ac50-4fff-b2dd-cb8cd8abeb2c,328,448,09511 Fisher Springs Suite 724,Compton,CA,90221,-118.271163,33.943150
1,BrHcJPwbEN,411056cb-ac50-4fff-b2dd-cb8cd8abeb2c,323,408,300 Campbell Circle Apt. 694,Torrance,CA,90501,-118.344604,33.949888
2,CrrIMbxCqq,ad3f9a5b-bd16-4fa7-955f-a64efcbe0b73,256,484,88884 Sophia Crest Apt. 875,San Diego,CA,92115,-117.120404,32.760434
3,DTkbsfedVz,ea4d744e-81be-4c5b-a9fe-6635bdc73898,319,493,92227 Mclaughlin Junction Suite 491,Lake Elsinore,CA,92532,-117.341477,33.730245
4,EiYBogVros,c2ce04c8-903e-4cf8-a0c9-2e486c6505f8,301,426,33842 Jones Glens Apt. 143,Glendora,CA,91740,-117.839645,34.140117
...,...,...,...,...,...,...,...,...,...,...
80,vKDywjAzZd,a08f28d3-8199-4ec8-9246-b2d753201981,335,490,61775 Scott Prairie,La Mirada,CA,90638,-118.089766,33.955456
81,vwBwugVAWN,419fbe0b-fe20-4402-85ab-3a02188518d1,221,406,889 Andrea Brooks,Manteca,CA,95337,-121.227263,37.826245
82,yGPwyiMcbi,2b72db98-be02-4834-900f-70129f665910,146,414,08013 Sutton Prairie Apt. 637,Diamond Bar,CA,91765,-117.870939,34.089176
83,yGPwyiMcbi,c7215c9d-c948-40c9-9436-87359f76087d,169,414,08013 Sutton Prairie Apt. 637,Diamond Bar,CA,91765,-117.870939,34.089176
84,zbozWvFTfr,dc50cc89-f7ed-4469-a19e-b0f675ec0110,352,454,56213 Steele Run,Downey,CA,90242,-118.162333,33.928488

In [35]:
purchase_df = add_temp_df[['family_id', 'super_market_uuid', 'total', 'longitude', 'latitude']]
purchase_df

,family_id,super_market_uuid,total,longitude,latitude
0,AmBEinMYuA,411056cb-ac50-4fff-b2dd-cb8cd8abeb2c,328,-118.271163,33.943150
1,BrHcJPwbEN,411056cb-ac50-4fff-b2dd-cb8cd8abeb2c,323,-118.344604,33.949888
2,CrrIMbxCqq,ad3f9a5b-bd16-4fa7-955f-a64efcbe0b73,256,-117.120404,32.760434
3,DTkbsfedVz,ea4d744e-81be-4c5b-a9fe-6635bdc73898,319,-117.341477,33.730245
4,EiYBogVros,c2ce04c8-903e-4cf8-a0c9-2e486c6505f8,301,-117.839645,34.140117
...,...,...,...,...,...
80,vKDywjAzZd,a08f28d3-8199-4ec8-9246-b2d753201981,335,-118.089766,33.955456
81,vwBwugVAWN,419fbe0b-fe20-4402-85ab-3a02188518d1,221,-121.227263,37.826245
82,yGPwyiMcbi,2b72db98-be02-4834-900f-70129f665910,146,-117.870939,34.089176
83,yGPwyiMcbi,c7215c9d-c948-40c9-9436-87359f76087d,169,-117.870939,34.089176
84,zbozWvFTfr,dc50cc89-f7ed-4469-a19e-b0f675ec0110,352,-118.162333,33.928488

In [36]:
import plotly.express as px
import plotly.figure_factory as ff
import numpy as np
MAPBOX_TOKEN = 'pk.eyJ1IjoiZm9kZ2Fib3JtYXRoIiwiYSI6ImNrZmY3Nzc2bjBiemkyeG8zdGNzcXgzMGIifQ.J0dZhMiuZTPVexL8nrpS6Q'
px.set_mapbox_access_token(MAPBOX_TOKEN)

In [39]:
fig = px.density_mapbox(purchase_df, lat='latitude', lon='longitude', z='total', radius=10,
                        center=dict(lat=41.3, lon=-96.1), zoom=3,
                        height=600,
                        mapbox_style="stamen-terrain")
fig.update_layout(margin=dict(b=0,t=0,l=0,r=0))
fig.show()

In [40]:
all_stores

,Unnamed: 0,name,latitude,longitude,store_id
0,0,Conway Supercenter,35.108660,-92.436905,5eb5e7fc-88b6-4326-9f6f-c2bfee082258
1,1,Sikeston Supercenter,36.857394,-89.586051,03419f7a-e60f-4b7b-9bea-edff19c1a24a
2,2,Tahlequah Supercenter,35.888765,-94.979859,a7b1bc6a-17b6-4de1-ae2e-eecd653bf891
3,3,Mountain Home Supercenter,36.354957,-92.341026,bf317faf-d154-4980-a8d1-83161bfbbacf
4,4,Claremore Supercenter,36.293955,-95.627125,04508372-c00b-4e4c-a486-524e9730040f
...,...,...,...,...,...
4649,4649,Pearland Neighborhood Market,29.556350,-95.415783,8c4f0c6f-4cfb-40d9-8034-07d92f28ad03
4650,4650,Bentonville Gas Station,36.357486,-94.214669,c59fa17d-5db0-4fc9-87d7-d84a1944293d
4651,4651,Millcreek Pickup only,40.691031,-111.846529,c070b01a-bb77-4587-ab85-d7e29819f9c5
4652,4652,Dallas Supercenter,32.963412,-96.770294,25ffd0bb-0501-4418-801e-2f55f833f8f6
4653,4653,Murray Pickup only,40.649827,-111.849349,974573f3-e900-4b4c-bd49-5001805386a9

In [44]:
stores_geo_df = pd.read_csv(stores_with_geo)
stores_geo_df

      Unnamed: 0                          name state   latitude   longitude
0              0            Conway Supercenter    AR  35.108660  -92.436905
1              1          Sikeston Supercenter    MO  36.857394  -89.586051
2              2         Tahlequah Supercenter    OK  35.888765  -94.979859
3              3     Mountain Home Supercenter    AR  36.354957  -92.341026
4              4         Claremore Supercenter    OK  36.293955  -95.627125
...          ...                           ...   ...        ...         ...
4649        4649  Pearland Neighborhood Market    TX  29.556350  -95.415783
4650        4650       Bentonville Gas Station    AR  36.357486  -94.214669
4651        4651         Millcreek Pickup only    UT  40.691031 -111.846529
4652        4652            Dallas Supercenter    TX  32.963412  -96.770294
4653        4653            Murray Pickup only    UT  40.649827 -111.849349

[4654 rows x 5 columns]

In [45]:
stores_geo_df = stores_geo_df[stores_geo_df['state'] == 'CA']

In [47]:
stores_geo_df = stores_geo_df[['name', 'latitude', 'longitude']]

In [48]:
stores_geo_df

                                 name   latitude   longitude
1489             Stockton Supercenter  38.023504 -121.273567
1491            El Centro Supercenter  32.813411 -115.577324
1502            Lancaster Supercenter  34.693755 -118.174112
1510             Oroville Supercenter  39.496607 -121.573430
1516                     Madera Store  36.975625 -120.080610
...                               ...        ...         ...
4464      Lincoln Neighborhood Market  38.888601 -121.291797
4465  Granite Bay Neighborhood Market  38.742435 -121.224989
4467   Sacramento Neighborhood Market  38.616999 -121.399030
4474                  Escondido Store  33.130137 -117.062977
4512   Sacramento Neighborhood Market  38.494354 -121.454151

[281 rows x 3 columns]

In [53]:
stores_temp_df = pd.merge(stores_geo_df, all_stores, how='left', on='name')
stores_temp_df

,name,latitude_x,longitude_x,Unnamed: 0,latitude_y,longitude_y,store_id
0,Stockton Supercenter,38.023504,-121.273567,1489,38.023504,-121.273567,037797a3-acf8-47a7-9e92-aff601545ed6
1,Stockton Supercenter,38.023504,-121.273567,3035,38.049823,-121.376304,e8040577-9276-406c-9261-51cfc4d5036d
2,El Centro Supercenter,32.813411,-115.577324,1491,32.813411,-115.577324,2d3349b6-b5f4-465f-9191-92918606ae7b
3,Lancaster Supercenter,34.693755,-118.174112,448,32.592150,-96.819145,3ea764c4-3850-4251-bdfe-f83982107a58
4,Lancaster Supercenter,34.693755,-118.174112,984,34.734251,-80.784758,65edd0d7-6cc8-4de0-a422-b4e390e7247a
...,...,...,...,...,...,...,...
451,Sacramento Neighborhood Market,38.616999,-121.399030,4467,38.616999,-121.399030,33c65afc-65f5-4d40-8f35-1c00a94dc8c7
452,Sacramento Neighborhood Market,38.616999,-121.399030,4512,38.494354,-121.454151,190c734e-e701-4968-a2ed-ae9f1e110feb
453,Escondido Store,33.130137,-117.062977,4474,33.130137,-117.062977,150e5a43-10b4-4dd6-9747-a93cfed08903
454,Sacramento Neighborhood Market,38.494354,-121.454151,4467,38.616999,-121.399030,33c65afc-65f5-4d40-8f35-1c00a94dc8c7
455,Sacramento Neighborhood Market,38.494354,-121.454151,4512,38.494354,-121.454151,190c734e-e701-4968-a2ed-ae9f1e110feb

In [54]:
stores_viz_df = stores_temp_df[['name', 'store_id', 'latitude_x', 'longitude_x']]
stores_viz_df

,name,store_id,latitude_x,longitude_x
0,Stockton Supercenter,037797a3-acf8-47a7-9e92-aff601545ed6,38.023504,-121.273567
1,Stockton Supercenter,e8040577-9276-406c-9261-51cfc4d5036d,38.023504,-121.273567
2,El Centro Supercenter,2d3349b6-b5f4-465f-9191-92918606ae7b,32.813411,-115.577324
3,Lancaster Supercenter,3ea764c4-3850-4251-bdfe-f83982107a58,34.693755,-118.174112
4,Lancaster Supercenter,65edd0d7-6cc8-4de0-a422-b4e390e7247a,34.693755,-118.174112
...,...,...,...,...
451,Sacramento Neighborhood Market,33c65afc-65f5-4d40-8f35-1c00a94dc8c7,38.616999,-121.399030
452,Sacramento Neighborhood Market,190c734e-e701-4968-a2ed-ae9f1e110feb,38.616999,-121.399030
453,Escondido Store,150e5a43-10b4-4dd6-9747-a93cfed08903,33.130137,-117.062977
454,Sacramento Neighborhood Market,33c65afc-65f5-4d40-8f35-1c00a94dc8c7,38.494354,-121.454151
455,Sacramento Neighborhood Market,190c734e-e701-4968-a2ed-ae9f1e110feb,38.494354,-121.454151

In [55]:
stores_viz_df.columns = ['name', 'store_id', 'latitude', 'longitude']

In [56]:
stores_viz_df

,name,store_id,latitude,longitude
0,Stockton Supercenter,037797a3-acf8-47a7-9e92-aff601545ed6,38.023504,-121.273567
1,Stockton Supercenter,e8040577-9276-406c-9261-51cfc4d5036d,38.023504,-121.273567
2,El Centro Supercenter,2d3349b6-b5f4-465f-9191-92918606ae7b,32.813411,-115.577324
3,Lancaster Supercenter,3ea764c4-3850-4251-bdfe-f83982107a58,34.693755,-118.174112
4,Lancaster Supercenter,65edd0d7-6cc8-4de0-a422-b4e390e7247a,34.693755,-118.174112
...,...,...,...,...
451,Sacramento Neighborhood Market,33c65afc-65f5-4d40-8f35-1c00a94dc8c7,38.616999,-121.399030
452,Sacramento Neighborhood Market,190c734e-e701-4968-a2ed-ae9f1e110feb,38.616999,-121.399030
453,Escondido Store,150e5a43-10b4-4dd6-9747-a93cfed08903,33.130137,-117.062977
454,Sacramento Neighborhood Market,33c65afc-65f5-4d40-8f35-1c00a94dc8c7,38.494354,-121.454151
455,Sacramento Neighborhood Market,190c734e-e701-4968-a2ed-ae9f1e110feb,38.494354,-121.454151

In [58]:
fig = px.density_mapbox(purchase_df, lat='latitude', lon='longitude', z='total', radius=10,
                        center=dict(lat=41.3, lon=-96.1), zoom=3,
                        height=600,
                        mapbox_style="stamen-terrain")

fig.add_densitymapbox(lat=stores_viz_df['latitude'], lon=stores_viz_df['longitude'], 
                      colorscale = [[0, 'rgb(255,0,0)'], [1, 'rgb(255,0,0)']], 
                      radius=5 )
fig.update_layout(margin=dict(b=0,t=0,l=0,r=0))
fig.show()